version: '3.8'

services:
  oracle-bmcsdl:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    environment:
      - ORACLE_PWD=bmcsdl
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=express
    ports:
      - "1521:1521"  # TNS Listener
      - "5500:5500"  # EM Express
    volumes:
      - ./data:/opt/oracle/oradata
    shm_size: 2g     # Recommended for Oracle XE
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - oracle-network

networks:
  oracle-network:
    driver: bridge